#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

const { detectFamily, generateCode, parseCode } = require('./lib/core')
const runCommon = require('./plugins/common')
const runAwsc = require('./plugins/awsc')
const runObfuscator = require('./plugins/obfuscator')
const runSojson = require('./plugins/sojson')
const runSojsonV7 = require('./plugins/sojsonv7')

const pipelines = {
  common: runCommon,
  awsc: runAwsc,
  obfuscator: runObfuscator,
  sojson: runSojson,
  sojsonv7: runSojsonV7
}

function getArg(flag, fallback) {
  const index = process.argv.indexOf(flag)
  if (index === -1 || index + 1 >= process.argv.length) return fallback
  return process.argv[index + 1]
}

function normalizePath(value) {
  return process.platform === 'win32' ? value.toLowerCase() : value
}

function assertPlainDirectory(directory) {
  const canonical = fs.realpathSync.native(directory)
  const resolved = path.resolve(directory)
  if (normalizePath(canonical) !== normalizePath(resolved)) {
    throw new Error(`refusing output through a symlink or junction: ${directory}`)
  }
  return canonical
}

function sameFile(left, right) {
  return left.dev === right.dev && left.ino === right.ino
}

function unlinkIfSame(file, expected) {
  try {
    if (sameFile(fs.lstatSync(file), expected)) fs.unlinkSync(file)
  } catch (error) {
    if (error.code !== 'ENOENT') throw error
  }
}

function writeExclusive(outputFile, content) {
  const directory = path.dirname(outputFile)
  const canonicalDirectory = assertPlainDirectory(directory)
  const temporary = path.join(directory, `.${path.basename(outputFile)}.${process.pid}.${process.hrtime.bigint()}.tmp`)
  let descriptor
  let temporaryIdentity
  let published = false
  try {
    descriptor = fs.openSync(temporary, 'wx', 0o600)
    temporaryIdentity = fs.fstatSync(descriptor)
    if (normalizePath(path.dirname(fs.realpathSync.native(temporary))) !== normalizePath(canonicalDirectory)) {
      throw new Error(`temporary output escaped the approved directory: ${temporary}`)
    }
    fs.linkSync(temporary, outputFile)
    const outputIdentity = fs.lstatSync(outputFile)
    if (!sameFile(outputIdentity, temporaryIdentity) ||
        normalizePath(path.dirname(fs.realpathSync.native(outputFile))) !== normalizePath(canonicalDirectory)) {
      throw new Error(`published output escaped the approved directory: ${outputFile}`)
    }
    fs.writeFileSync(descriptor, content, { encoding: 'utf8' })
    fs.fsyncSync(descriptor)
    if (!sameFile(fs.lstatSync(outputFile), temporaryIdentity)) {
      throw new Error(`published output was replaced during write: ${outputFile}`)
    }
    published = true
  } finally {
    if (descriptor !== undefined) fs.closeSync(descriptor)
    if (!published && temporaryIdentity) unlinkIfSame(outputFile, temporaryIdentity)
    if (temporaryIdentity) unlinkIfSame(temporary, temporaryIdentity)
  }
}

function main() {
  const inputFile = path.resolve(getArg('-i', path.resolve(process.cwd(), 'input.js')))
  const outputFile = path.resolve(getArg('-o', path.resolve(process.cwd(), 'output.js')))
  if (inputFile === outputFile) throw new Error('input and output paths must differ')
  if (fs.existsSync(outputFile)) throw new Error(`refusing to overwrite existing output: ${outputFile}`)
  const code = fs.readFileSync(inputFile, 'utf8')
  const executeBootstrap = process.argv.includes('--execute-bootstrap')
  const trustedBootstrap = process.argv.includes('--trusted-bootstrap')
  const aggressive = process.argv.includes('--aggressive')

  if (executeBootstrap && !trustedBootstrap) {
    throw new Error('--execute-bootstrap requires --trusted-bootstrap after source review')
  }

  const family = detectFamily(code)
  const transform = pipelines[family] || runCommon
  const result = generateCode(transform(parseCode(code), { executeBootstrap, trustedBootstrap, aggressive }))
  parseCode(result)

  const banner = [
    '// generated by the web-protocol-recovery AST template project',
    `// plugin: ${family}`,
    `// input: ${path.basename(inputFile)}`,
    ''
  ].join('\n')

  writeExclusive(outputFile, banner + result)
  console.log(`plugin=${family}`)
  console.log(`executeBootstrap=${executeBootstrap}`)
  console.log(`aggressive=${aggressive}`)
  console.log(`output=${outputFile}`)
}

main()
